sonar.projectKey=ridematch-ai
sonar.projectName=RideMatch AI
sonar.organization=ashwin1808

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/dist/**

sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io