apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: ridematch

type: Opaque

stringData:

  DB_PASSWORD: ""
  JWT_SECRET: ""
  GEMINI_API_KEY: ""
  NEWS_API_KEY: ""
  GNEWS_API_KEY: ""