apiVersion: batch/v1
kind: Job

metadata:
  name: ridematch-failing-job
  namespace: ridematch

spec:
  backoffLimit: 3

  template:
    spec:
      containers:
        - name: failing-job
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Starting RideMatch task..."
              echo "Something went wrong!"
              exit 1

      restartPolicy: Never