apiVersion: apps/v1
kind: Deployment

metadata:
  name: ridematch-backend
  namespace: ridematch

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ridematch-backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: ridematch-backend

    spec:
      containers:
        - name: backend
          image: ashwindocker1808/ridematch-backend:v3
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          ports:
            - containerPort: 5001

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


          startupProbe:
            httpGet:
              path: /health
              port: 5001

            periodSeconds: 10
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2